on:
  push:
    branches:
    - vanilla
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.HOST }}
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
    - name: Build and deploy search list
      run: |
        cd search && yarn && yarn build
        ls
    - name: Deploy map to server
      run: |
            scp -r -o "StrictHostKeyChecking no" ./map/* ${{secrets.USERNAME}}@${{ secrets.HOST }}:/var/www/html/
