on:
  push:
    branches:
    - vanilla
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Create key
      run: echo "${{ secrets.SSH_KEY }}" > key.cer
    - name: Deploy to server
      run: |
            scp -i ./key.cer -r * ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/
